const TIPOS_NOTIFICACAO = Object.freeze({
    INTERESSE_RECEBIDO: "INTERESSE_RECEBIDO",
    INTERESSE_ACEITO: "INTERESSE_ACEITO",
    INTERESSE_RECUSADO: "INTERESSE_RECUSADO",
    INTERESSE_CANCELADO: "INTERESSE_CANCELADO",
    DOACAO_CONFIRMADA: "DOACAO_CONFIRMADA",
    AVALIACAO_RECEBIDA: "AVALIACAO_RECEBIDA",
    DENUNCIA_RESULTADO: "DENUNCIA_RESULTADO",
    USUARIO_SUSPENSO: "USUARIO_SUSPENSO",
    USUARIO_REATIVADO: "USUARIO_REATIVADO",
    ITEM_CANCELADO: "ITEM_CANCELADO",
    SISTEMA: "SISTEMA",
});

const REFERENCIAS_NOTIFICACAO = Object.freeze({
    INTERESSE: "INTERESSE",
    ITEM: "ITEM",
    DENUNCIA: "DENUNCIA",
    USUARIO: "USUARIO",
});

export { TIPOS_NOTIFICACAO, REFERENCIAS_NOTIFICACAO };
